name: .NET

on: [push]
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      #run: dotnet build --no-restore
      run: dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true --self-contained true
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: bin/Release/net5.0/win-x64/publish/TCS.exe
        #body_path: ${{ github.workflow }}-CHANGELOG.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
